// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkrPk0TQSB1I2mnNHNvvWyDWBubR_erzk',
    appId: '1:665503474790:web:ab57447bed696619b0b9a7',
    messagingSenderId: '665503474790',
    projectId: 'pharmconnect-cd6f1',
    authDomain: 'pharmconnect-cd6f1.firebaseapp.com',
    storageBucket: 'pharmconnect-cd6f1.firebasestorage.app',
    measurementId: 'G-1G7HWNGVDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoAfyW_16oxifrMmmBrejru4ym-xDMP-s',
    appId: '1:665503474790:android:537a29b6549fe7c7b0b9a7',
    messagingSenderId: '665503474790',
    projectId: 'pharmconnect-cd6f1',
    storageBucket: 'pharmconnect-cd6f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5sA95knj3Je5C2H3FtJbzf7k7nooLY5M',
    appId: '1:665503474790:ios:36db422f9de1ab59b0b9a7',
    messagingSenderId: '665503474790',
    projectId: 'pharmconnect-cd6f1',
    storageBucket: 'pharmconnect-cd6f1.firebasestorage.app',
    iosBundleId: 'com.example.pharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5sA95knj3Je5C2H3FtJbzf7k7nooLY5M',
    appId: '1:665503474790:ios:36db422f9de1ab59b0b9a7',
    messagingSenderId: '665503474790',
    projectId: 'pharmconnect-cd6f1',
    storageBucket: 'pharmconnect-cd6f1.firebasestorage.app',
    iosBundleId: 'com.example.pharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkrPk0TQSB1I2mnNHNvvWyDWBubR_erzk',
    appId: '1:665503474790:web:769f5e9eb625f7edb0b9a7',
    messagingSenderId: '665503474790',
    projectId: 'pharmconnect-cd6f1',
    authDomain: 'pharmconnect-cd6f1.firebaseapp.com',
    storageBucket: 'pharmconnect-cd6f1.firebasestorage.app',
    measurementId: 'G-D51ECM8E3H',
  );
}
